-- =====================================================================
-- setup.sql — Script lengkap database untuk Supabase
-- ---------------------------------------------------------------------
-- CARA PAKAI:
--   1. Buka Supabase Dashboard -> SQL Editor -> New query
--   2. Tempel seluruh isi file ini -> Run
--
-- Script ini IDEMPOTEN (aman dijalankan berulang), jadi cocok baik untuk
-- database BARU maupun database LAMA yang sudah punya tabel:
--   * tabel/kolom yang sudah ada dilewati (IF NOT EXISTS)
--   * policy lama yang tidak aman dibuang, lalu dipasang versi barunya
--
-- Isinya sudah mencakup dua perbaikan keamanan:
--   A. Proyek yang BELUM dipublikasikan tidak bisa dibaca lewat API anon
--      (policy SELECT publik hanya mengembalikan is_published != false)
--   B. Bucket profile-images hanya menerima upload file GAMBAR
--      (tanpa ini, siapa pun bisa menyimpan file apa pun ke bucket publik)
--
-- Catatan: bila Anda memakai Supabase CLI, versi incremental yang sama
-- juga tersedia di supabase/migrations/*.sql — jalankan salah satu saja
-- (keduanya sama-sama idempoten, jadi tidak masalah kalau keduanya).
-- =====================================================================


-- =====================================================================
-- 1. TABEL
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title" text,
  "Description" text,
  "Img" text,
  "Link" text,
  "Github" text,
  "Features" jsonb,
  "TechStack" jsonb,
  is_published boolean DEFAULT true,
  order_index int DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.certificates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Img" text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.portfolio_comments (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  content text NOT NULL,
  user_name text NOT NULL,
  profile_image text,
  is_pinned boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username text UNIQUE NOT NULL,
  role text NOT NULL CHECK (role IN ('admin', 'user')),
  created_at timestamptz DEFAULT now()
);

-- Database lama yang dibuat sebelum kolom publish/urutan ada:
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS is_published boolean DEFAULT true;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS order_index integer DEFAULT 0;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.certificates ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.portfolio_comments ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

-- Proyek lama yang belum punya nilai dianggap terpublikasi, supaya tidak
-- ada proyek yang mendadak hilang dari situs.
UPDATE public.projects
SET is_published = true
WHERE is_published IS NULL;


-- =====================================================================
-- 2. ROW LEVEL SECURITY
-- =====================================================================

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------
-- profiles: user hanya boleh membaca profilnya sendiri
-- (dibutuhkan login untuk mengecek role)
-- ---------------------------------------------------------------------
DROP POLICY IF EXISTS "User can read own profile" ON public.profiles;
CREATE POLICY "User can read own profile"
ON public.profiles FOR SELECT TO authenticated
USING ((SELECT auth.uid()) = id);

-- ---------------------------------------------------------------------
-- projects
--   * publik : HANYA proyek terpublikasi (perbaikan A)
--   * admin  : semua baris + insert/update/delete
-- ---------------------------------------------------------------------
DROP POLICY IF EXISTS "public read projects" ON public.projects;      -- policy lama (USING true) yang bocor
DROP POLICY IF EXISTS "public read published projects" ON public.projects;
DROP POLICY IF EXISTS "admin manage projects" ON public.projects;

CREATE POLICY "public read published projects"
ON public.projects
FOR SELECT
USING (is_published IS NOT FALSE);

CREATE POLICY "admin manage projects"
ON public.projects FOR ALL
USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
)
WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- ---------------------------------------------------------------------
-- certificates
-- ---------------------------------------------------------------------
DROP POLICY IF EXISTS "public read certificates" ON public.certificates;
DROP POLICY IF EXISTS "admin manage certificates" ON public.certificates;

CREATE POLICY "public read certificates"
ON public.certificates FOR SELECT USING (true);

CREATE POLICY "admin manage certificates"
ON public.certificates FOR ALL
USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
)
WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- ---------------------------------------------------------------------
-- portfolio_comments
--   * publik : baca semua + insert (tapi tidak pernah insert pinned)
--   * admin  : semua (pin/unpin/delete), harus login
-- ---------------------------------------------------------------------
DROP POLICY IF EXISTS "public read comments" ON public.portfolio_comments;
DROP POLICY IF EXISTS "public insert comment" ON public.portfolio_comments;
DROP POLICY IF EXISTS "admin manage comments" ON public.portfolio_comments;

CREATE POLICY "public read comments"
ON public.portfolio_comments FOR SELECT USING (true);

CREATE POLICY "public insert comment"
ON public.portfolio_comments FOR INSERT
WITH CHECK (is_pinned = false);

CREATE POLICY "admin manage comments"
ON public.portfolio_comments FOR ALL TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
)
WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);


-- =====================================================================
-- 3. STORAGE: bucket + policy
-- =====================================================================

INSERT INTO storage.buckets (id, name, public)
VALUES
  ('project-images', 'project-images', true),
  ('certificate-images', 'certificate-images', true),
  ('profile-images', 'profile-images', true)
ON CONFLICT DO NOTHING;

-- Gambar proyek & sertifikat: hanya admin yang boleh mengunggah.
DROP POLICY IF EXISTS "admin upload project images" ON storage.objects;
DROP POLICY IF EXISTS "public read project images" ON storage.objects;
DROP POLICY IF EXISTS "admin upload certificate images" ON storage.objects;
DROP POLICY IF EXISTS "public read certificate images" ON storage.objects;

CREATE POLICY "admin upload project images"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'project-images'
  AND EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

CREATE POLICY "public read project images"
ON storage.objects FOR SELECT
USING (bucket_id = 'project-images');

CREATE POLICY "admin upload certificate images"
ON storage.objects FOR INSERT
WITH CHECK (
  bucket_id = 'certificate-images'
  AND EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

CREATE POLICY "public read certificate images"
ON storage.objects FOR SELECT
USING (bucket_id = 'certificate-images');

-- Foto profil komentar: publik boleh mengunggah, TAPI hanya file gambar
-- (perbaikan B). Policy lama tanpa filter dibuang:
DROP POLICY IF EXISTS "public upload profile images" ON storage.objects;
DROP POLICY IF EXISTS "profile images are images only" ON storage.objects;

CREATE POLICY "profile images are images only"
ON storage.objects FOR INSERT
TO public
WITH CHECK (
  bucket_id = 'profile-images'
  AND name ~* '\.(jpg|jpeg|png|gif|webp|avif)$'
);

DROP POLICY IF EXISTS "public read profile images" ON storage.objects;
CREATE POLICY "public read profile images"
ON storage.objects FOR SELECT
USING (bucket_id = 'profile-images');


-- =====================================================================
-- 4. REALTIME untuk komentar
--    (cara manual: Table Editor -> portfolio_comments -> Enable Realtime)
--    Script ini mendaftarkannya otomatis bila publication-nya ada.
-- =====================================================================

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
     AND NOT EXISTS (
       SELECT 1 FROM pg_publication_tables
       WHERE pubname = 'supabase_realtime'
         AND schemaname = 'public'
         AND tablename = 'portfolio_comments'
     ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.portfolio_comments;
  END IF;
END $$;


-- =====================================================================
-- 5. Komentar pinned bawaan (tidak menduplikasi bila sudah ada)
-- =====================================================================

INSERT INTO public.portfolio_comments (content, user_name, profile_image, is_pinned)
SELECT
  'developed by ekizr. This project is open-source and free to use.',
  'ekizr',
  'https://egwzigagwyrmwjsrebzx.supabase.co/storage/v1/object/public/profile-images/profile-images/1771939421615_xx2q8hgya6e.jpeg',
  true
WHERE NOT EXISTS (
  SELECT 1 FROM public.portfolio_comments WHERE is_pinned = true
);


-- =====================================================================
-- 6. AKUN ADMIN (isi dulu USER_UUID dengan Auth -> Users -> Copy User ID)
-- =====================================================================
-- INSERT INTO public.profiles (id, username, role)
-- VALUES ('USER_UUID', 'eki', 'admin')
-- ON CONFLICT (id) DO UPDATE SET role = 'admin';


-- =====================================================================
-- 7. VERIFIKASI (jalankan satu per satu, sebagai query terpisah)
-- =====================================================================

-- Seharusnya hanya mengembalikan baris terpublikasi (sebagai anon):
--   SET ROLE anon;
--   SELECT id, "Title", is_published FROM public.projects;
--   RESET ROLE;

-- Policy projects harus berisi "public read published projects" dan
-- "admin manage projects" — TANPA "public read projects":
--   SELECT policyname, cmd, qual FROM pg_policies
--   WHERE schemaname = 'public' AND tablename = 'projects';

-- Upload non-gambar ke profile-images harus ditolak di aplikasi,
-- dan daftar policy storage harus memuat "profile images are images only":
--   SELECT policyname, cmd, qual FROM pg_policies
--   WHERE schemaname = 'storage' AND tablename = 'objects';
